"""
metaheuristicas.py
==================
Two metaheuristic optimisers for binary-vector search spaces.

Both share the same interface so they are interchangeable in run_experiment:

    best_solution, solutions_dict = optimiser(
        objective_function,   # f(vector) -> (cost: float, aux: any)
        chromosome_length,    # int
        **kwargs
    )

The objective_function must be *minimised* (lower cost = better).
Since we maximise accuracy, pass  cost = -accuracy.
"""

import random
import math
import numpy as np

# ─────────────────────────────────────────────────────────────────────────────
#  SIMULATED ANNEALING (binary)
# ─────────────────────────────────────────────────────────────────────────────

def simulated_annealing(
    objective_function,
    chromosome_length,
    initial_solution=None,
    initial_temp=100.0,
    cooling_rate=0.95,
    stopping_temp=1e-3,
    max_iterations=10,
    num_neighbors=5,
    seed=12345,
):
    """
    Simulated annealing for binary vectors.

    At each temperature step, `num_neighbors` candidates are generated by
    flipping a random bit. A worse candidate is accepted with probability
    exp(Δcost / T), which allows escaping local optima early in the search.

    Parameters
    ----------
    objective_function : callable
        f(vector: list[int]) -> (cost: float, aux: any).  Minimised.
    chromosome_length  : int
        Length of the binary vector.
    initial_solution   : list[int] | None
        Starting point.  Random if None.
    initial_temp       : float
        Starting temperature.
    cooling_rate       : float
        Multiplicative cooling factor applied each iteration (< 1).
    stopping_temp      : float
        Algorithm halts when T falls below this value.
    max_iterations     : int
        Maximum number of temperature steps.
    num_neighbors      : int
        Candidates evaluated per step.
    seed               : int
        Random seed for reproducibility.

    Returns
    -------
    best_solution : list[int]
    solutions_dict : dict  — every evaluated solution keyed by str(vector).
    """
    random.seed(seed)
    solutions_dict = {}

    def _evaluate(vec):
        key = str(vec)
        if key not in solutions_dict:
            cost, aux = objective_function(vec)
            solutions_dict[key] = {"solution": vec[:], "cost": cost, "aux": aux}
        return solutions_dict[str(vec)]["cost"]

    current = initial_solution if initial_solution is not None \
        else [random.randint(0, 1) for _ in range(chromosome_length)]
    current_cost = _evaluate(current)
    best, best_cost = current[:], current_cost

    temp = initial_temp
    iteration = 0
    while temp > stopping_temp and iteration < max_iterations:
        for _ in range(num_neighbors):
            candidate = current[:]
            idx = random.randint(0, chromosome_length - 1)
            candidate[idx] ^= 1
            candidate_cost = _evaluate(candidate)

            delta = candidate_cost - current_cost
            if delta < 0 or random.random() < math.exp(-delta / temp):
                current, current_cost = candidate[:], candidate_cost

            if current_cost < best_cost:
                best, best_cost = current[:], current_cost

        temp *= cooling_rate
        iteration += 1
        print(f"  [SA] iter={iteration:>3}  T={temp:.4f}  best_cost={best_cost:.4f}")

    return best, solutions_dict


# ─────────────────────────────────────────────────────────────────────────────
#  GENETIC ALGORITHM (binary)
# ─────────────────────────────────────────────────────────────────────────────

def genetic_algorithm(
    objective_function,
    chromosome_length,
    population_size=20,
    n_generations=10,
    crossover_rate=0.8,
    mutation_rate=None,
    tournament_size=3,
    elitism_count=1,
    seed=12345,
):
    """
    Steady-state genetic algorithm for binary optimisation.

    Operators
    ---------
    Selection   : k-tournament (pressure controlled by `tournament_size`).
    Crossover   : uniform crossover (each bit independently chosen from
                  either parent with probability 0.5).
    Mutation    : bit-flip with per-bit probability `mutation_rate`
                  (default 1/chromosome_length — the canonical setting).
    Elitism     : the top `elitism_count` individuals always survive.

    This combination is well-suited to binary feature-selection / entanglement-
    map search: uniform crossover preserves useful bit patterns regardless of
    position, while tournament selection controls exploration without needing
    fitness scaling.

    Parameters
    ----------
    objective_function : callable
        f(vector: list[int]) -> (cost: float, aux: any).  Minimised.
    chromosome_length  : int
        Length of the binary vector.
    population_size    : int
        Number of individuals per generation.
    n_generations      : int
        Number of generations to evolve.
    crossover_rate     : float
        Probability that two parents undergo crossover (else offspring = copy).
    mutation_rate      : float | None
        Per-bit mutation probability.  Defaults to 1/chromosome_length.
    tournament_size    : int
        Candidates drawn for each tournament selection.
    elitism_count      : int
        Number of elite individuals copied unchanged into the next generation.
    seed               : int
        Random seed for reproducibility.

    Returns
    -------
    best_solution : list[int]
    solutions_dict : dict  — every evaluated solution keyed by str(vector).
    """
    random.seed(seed)
    np.random.seed(seed)

    if mutation_rate is None:
        mutation_rate = 1.0 / chromosome_length

    solutions_dict = {}

    # ── fitness with memoisation (quantum eval is expensive) ────────────────
    def _evaluate(vec):
        key = str(vec)
        if key not in solutions_dict:
            cost, aux = objective_function(vec)
            solutions_dict[key] = {"solution": vec[:], "cost": cost, "aux": aux}
        return solutions_dict[key]["cost"]

    # ── initialisation ───────────────────────────────────────────────────────
    population = [
        [random.randint(0, 1) for _ in range(chromosome_length)]
        for _ in range(population_size)
    ]
    fitness = [_evaluate(ind) for ind in population]

    best_idx  = int(np.argmin(fitness))
    best      = population[best_idx][:]
    best_cost = fitness[best_idx]
    print(f"  [GA] gen=  0  best_cost={best_cost:.4f}")

    # ── evolution loop ───────────────────────────────────────────────────────
    for gen in range(1, n_generations + 1):

        # Sort by fitness (ascending cost = descending quality)
        ranked = sorted(range(population_size), key=lambda i: fitness[i])
        elites = [population[i][:] for i in ranked[:elitism_count]]

        new_population = elites[:]

        while len(new_population) < population_size:
            # Tournament selection — parent A
            candidates_a = random.sample(range(population_size), tournament_size)
            parent_a = population[min(candidates_a, key=lambda i: fitness[i])][:]

            # Tournament selection — parent B
            candidates_b = random.sample(range(population_size), tournament_size)
            parent_b = population[min(candidates_b, key=lambda i: fitness[i])][:]

            # Uniform crossover
            if random.random() < crossover_rate:
                child = [
                    parent_a[i] if random.random() < 0.5 else parent_b[i]
                    for i in range(chromosome_length)
                ]
            else:
                child = parent_a[:]

            # Bit-flip mutation
            child = [bit ^ 1 if random.random() < mutation_rate else bit
                     for bit in child]

            new_population.append(child)

        population = new_population
        fitness    = [_evaluate(ind) for ind in population]

        gen_best_idx  = int(np.argmin(fitness))
        gen_best_cost = fitness[gen_best_idx]
        if gen_best_cost < best_cost:
            best_cost = gen_best_cost
            best      = population[gen_best_idx][:]

        print(f"  [GA] gen={gen:>3}  best_cost={best_cost:.4f}"
              f"  gen_best={gen_best_cost:.4f}"
              f"  evals={len(solutions_dict)}")

    return best, solutions_dict